version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:    
      "@babel":
        patterns:
          - "@babel/*"
      "@typescript-eslint":
        patterns:
          - "@typescript-eslint/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
