default_settings: &default_settings
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/repo

version: 2
jobs:
  setup:
    <<: *default_settings
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  deploy:
    <<: *default_settings
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "3e:af:55:2d:fc:b1:7c:09:9d:9d:d1:9e:50:ff:d4:15"
      - deploy:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "$GH_EMAIL"
            git config --global user.name "$GH_NAME"

            npm run deploy

workflows:
  version: 2
  build-accept-deploy:
    jobs:
      - setup
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - setup
          filters:
            branches:
              only: master
