name: Temp

on:
  workflow_run:
    workflows: [Test branch]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint
      - name: Run Cypress tests
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          build: npm run build:cy
          start: npm run serve:cy
          wait-on: "http://localhost:3000"